name: compras_jim_25
description: "Compras Jim 2025"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  google_maps_flutter: ^2.5.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
